import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    brier_score_loss,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split


NUMERIC_COLS = [
    "age",
    "bmi",
    "HbA1c_level",
    "blood_glucose_level",
    "hypertension",
    "heart_disease",
]

CATEGORICAL_COLS = [
    "gender",
    "smoking_history",
]

TARGET_COL = "diabetes"


@dataclass
class TrainArtifacts:
    model_payload: dict[str, Any]
    metrics: dict[str, float]
    sample_count: int
    positive_rate: float


def _normalize_dataset(df: pd.DataFrame) -> pd.DataFrame:
    required = NUMERIC_COLS + CATEGORICAL_COLS + [TARGET_COL]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset is missing required columns: {missing}")

    clean = df[required].copy()
    for col in NUMERIC_COLS + [TARGET_COL]:
        clean[col] = pd.to_numeric(clean[col], errors="coerce")

    for col in CATEGORICAL_COLS:
        clean[col] = clean[col].astype(str).fillna("No Info")
        clean[col] = clean[col].replace({"nan": "No Info", "None": "No Info"})

    clean = clean.dropna(subset=[TARGET_COL])
    clean[TARGET_COL] = clean[TARGET_COL].astype(int)

    # Numeric imputation
    numeric_defaults = {col: float(clean[col].median()) for col in NUMERIC_COLS}
    for col in NUMERIC_COLS:
        clean[col] = clean[col].fillna(numeric_defaults[col])

    return clean


def _train_rf(df: pd.DataFrame, n_estimators: int, max_depth: int) -> TrainArtifacts:
    clean = _normalize_dataset(df)
    y = clean[TARGET_COL].values

    x_num = clean[NUMERIC_COLS].astype(float).copy()
    x_cat = pd.get_dummies(clean[CATEGORICAL_COLS], prefix=CATEGORICAL_COLS, dtype=float)
    x_all = pd.concat([x_num, x_cat], axis=1)

    x_train, x_test, y_train, y_test = train_test_split(
        x_all, y, test_size=0.2, random_state=42, stratify=y
    )

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=20,
        max_features="sqrt",
        bootstrap=True,
        class_weight="balanced_subsample",
        random_state=42,
        n_jobs=-1,
    )
    model.fit(x_train, y_train)

    prob = model.predict_proba(x_test)[:, 1]
    pred = (prob >= 0.5).astype(int)

    metrics = {
        "roc_auc": float(roc_auc_score(y_test, prob)),
        "accuracy": float(accuracy_score(y_test, pred)),
        "f1": float(f1_score(y_test, pred, zero_division=0)),
        "precision": float(precision_score(y_test, pred, zero_division=0)),
        "recall": float(recall_score(y_test, pred, zero_division=0)),
        "brier": float(brier_score_loss(y_test, prob)),
    }

    defaults = {
        "numeric": {col: float(clean[col].median()) for col in NUMERIC_COLS},
        "gender": "Other",
        "smoking_history": "No Info",
    }

    trees = []
    for est in model.estimators_:
        t = est.tree_
        value = t.value.squeeze(axis=1)
        probs = []
        for row in value:
            total = float(np.sum(row))
            p1 = float(row[1] / total) if total > 0 and len(row) > 1 else 0.0
            probs.append(p1)
        trees.append(
            {
                "children_left": t.children_left.astype(int).tolist(),
                "children_right": t.children_right.astype(int).tolist(),
                "feature": t.feature.astype(int).tolist(),
                "threshold": t.threshold.astype(float).tolist(),
                "value": probs,
            }
        )

    payload = {
        "model_type": "random_forest_classifier",
        "version": "1.0.0",
        "target": TARGET_COL,
        "feature_order": x_all.columns.tolist(),
        "defaults": defaults,
        "class_names": ["no_diabetes", "diabetes"],
        "n_estimators": int(len(trees)),
        "metrics": metrics,
        "trees": trees,
    }

    return TrainArtifacts(
        model_payload=payload,
        metrics=metrics,
        sample_count=int(len(clean)),
        positive_rate=float(np.mean(y)),
    )


def _write_ts_model(payload: dict[str, Any], out_file: Path) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    model_json = json.dumps(payload, separators=(",", ":"), ensure_ascii=True)
    out_file.write_text(
        "/* Auto-generated by tools/train_diabetes_rf.py. Do not edit manually. */\n"
        f"export const diabetesRiskModel = {model_json} as const;\n"
        "export type DiabetesRiskModelData = typeof diabetesRiskModel;\n",
        encoding="utf-8",
    )


def _write_report(artifacts: TrainArtifacts, out_file: Path, data_file: Path) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    report = (
        "# Diabetes Random Forest Training Report\n\n"
        f"- Dataset: `{data_file}`\n"
        f"- Samples used: **{artifacts.sample_count}**\n"
        f"- Positive class rate (`diabetes=1`): **{artifacts.positive_rate:.4f}**\n\n"
        "## Holdout Metrics\n\n"
        f"- ROC-AUC: **{artifacts.metrics['roc_auc']:.4f}**\n"
        f"- Accuracy: **{artifacts.metrics['accuracy']:.4f}**\n"
        f"- F1: **{artifacts.metrics['f1']:.4f}**\n"
        f"- Precision: **{artifacts.metrics['precision']:.4f}**\n"
        f"- Recall: **{artifacts.metrics['recall']:.4f}**\n"
        f"- Brier: **{artifacts.metrics['brier']:.4f}**\n\n"
        "## Notes\n\n"
        "- This model is intended for in-app risk stratification and trend analytics.\n"
        "- It is not a standalone medical diagnosis.\n"
        "- Retrain periodically when dataset or feature distributions change.\n"
    )
    out_file.write_text(report, encoding="utf-8")


def _write_metrics_csv(artifacts: TrainArtifacts, out_file: Path, data_file: Path) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(
        [
            {
                "dataset_path": str(data_file),
                "samples_used": artifacts.sample_count,
                "positive_rate": artifacts.positive_rate,
                **artifacts.metrics,
            }
        ]
    )
    df.to_csv(out_file, index=False)


def _write_model_nodes_csv(payload: dict[str, Any], out_file: Path) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, Any]] = []
    trees: list[dict[str, Any]] = payload["trees"]
    for tree_index, tree in enumerate(trees):
        for node_index in range(len(tree["feature"])):
            rows.append(
                {
                    "tree_index": tree_index,
                    "node_index": node_index,
                    "feature_index": tree["feature"][node_index],
                    "feature_name": payload["feature_order"][tree["feature"][node_index]]
                    if tree["feature"][node_index] >= 0
                    else "",
                    "threshold": tree["threshold"][node_index],
                    "children_left": tree["children_left"][node_index],
                    "children_right": tree["children_right"][node_index],
                    "leaf_probability_diabetes": tree["value"][node_index],
                }
            )
    pd.DataFrame(rows).to_csv(out_file, index=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", required=True, help="Path to diabetes_prediction_dataset.csv")
    parser.add_argument(
        "--out-ts",
        default="src/lib/generated/diabetes-rf-model.ts",
        help="Output TypeScript model file",
    )
    parser.add_argument(
        "--out-report",
        default="model-artifacts/diabetes-rf-report.md",
        help="Output training report path",
    )
    parser.add_argument(
        "--out-metrics-csv",
        default="model-artifacts/diabetes-rf-metrics.csv",
        help="Output metrics CSV path",
    )
    parser.add_argument(
        "--out-model-csv",
        default="model-artifacts/diabetes-rf-model-nodes.csv",
        help="Output model nodes CSV path",
    )
    parser.add_argument("--n-estimators", type=int, default=60)
    parser.add_argument("--max-depth", type=int, default=8)
    args = parser.parse_args()

    data_file = Path(args.data)
    if not data_file.exists():
        raise FileNotFoundError(f"Dataset not found: {data_file}")

    df = pd.read_csv(data_file)
    artifacts = _train_rf(df, n_estimators=args.n_estimators, max_depth=args.max_depth)
    _write_ts_model(artifacts.model_payload, Path(args.out_ts))
    _write_report(artifacts, Path(args.out_report), data_file)
    _write_metrics_csv(artifacts, Path(args.out_metrics_csv), data_file)
    _write_model_nodes_csv(artifacts.model_payload, Path(args.out_model_csv))
    print(json.dumps({"ok": True, "metrics": artifacts.metrics}, indent=2))


if __name__ == "__main__":
    main()
